### ISSUE TITLE
Issues with importing expertai on Ubuntu 18.04

### ISSUE THREAD

**Issue by selin-k** [therealexpertai/nlapi-python#1]
Hi there,

I've been trying to extract topics out of articles using the expertai API. I've been successfully doing this locally on my Windows 10 pc; however, taking the script over to my Ubuntu 18.04 VPS I've been getting a - ModuleNotFoundError: No module named 'expertai'.

I've followed all instructions given - cloned the repo and installed all dependencies with pip3 and I'm running the script with python3. 

Script used:

```python
import os

os.chdir(r"/videogenerators/processing/nlapi-python") # path to cloned directory
from expertai.client import ExpertAiClient

os.environ["EAI_USERNAME"] = "..."
os.environ["EAI_PASSWORD"] = "..."
eai = ExpertAiClient()
language = 'en'
text = "some article..."
response = eai.full_analysis(body={"document": {"text":text}}, params={'language': language})
data = response.json["data"]

for label in data["topics"]:
    if label["winner"] == True:
        print(label["label"])
```

I know the path is correct for sure. What else could be the issue?

Cheers,
Selin

**Comment by andreabelli-eai** [comment]
Ciao Selin,
   it's possible that the python runtime is not finding the module expertai; it could be an path issue.
   Anyway, we uploaded a compiled library for nlapi on pip now with version 1.2.1 that you can install with 

`pip install expertai-nlapi`

  then you can get the categories as follows

```
document= client.iptc_media_topics_classification(body={"document": {"text": text}}, params={'language': language})
for category in document.categories:
    print (f'{category.label:{27}} {category.id_:{10}}{category.frequency:{8}}')
```

I hope it helps.
Andrea
