### ISSUE TITLE
expertai.nlapi.common.errors.ExpertAiRequestError: Response status code: 500 - Python SDK 

### ISSUE THREAD

**Issue by AndrewCrider** [therealexpertai/nlapi-python#10]
Successfully installed expertai-nlapi-2.1.3 - So I don't think it is the same problem as a previously closed item.

I have an export from a product (Roam Research) that is return results in a psedu-markdown template.  I've extracted it out and then run the following code to clean it up a little bit:

`eaiString = eaiString + s.get('string').replace('\n', ' ').replace('\r', ' ').replace('{',' ').replace('}',' ') + "\n"`
I then called the SDK with the following code

```
document = client.specific_resource_analysis(
        body={"document": {"text":text}}, 
        params={'language':'en', 'resource': 'relevants'})
```

The text is about 6500 lines and 658k characters.

I had submitted a much smaller excerpt earlier with out any problems so I don't think its an authentication issue.

**Comment by swelcker** [comment]
I guess you ran into the 10k Char limit

**Comment by AndrewCrider** [comment]
Thanks!  I properly escaped all the characters and got past that 500 error.

I'm now getting a bearer token:  
`expertai.nlapi.common.errors.ExpertAiRequestError: Failed to fetch the Bearer Token. Error: 504-Gateway Time-out`

I'm on a Mac (Big Sur - Version 11.2.1) running the latest version of the library and Python 3.7.7

**Comment by swelcker** [comment]
I guess you are using the Freemium SaaS NL API and not the Freemium Edge NL API , anyhow, it is a common and good practice, given the size of the text, to process the text in slices (chuncks) and just merge the JSON results. Using the edge NL API on your own HW may resolve this issue too. Hope that helps

**Comment by AndrewCrider** [comment]
Chunking out the text into smaller text blocks solved the issue.

Thanks,
