### ISSUE TITLE
Endpoint for sending multiple requests

### ISSUE THREAD

**Issue by deven-gqc** [therealexpertai/nlapi-python#13]
Hello, 
I was a participant from the expert.ai's NLP hackathon. I was using the API for to find sentiments of around 700 tweets.  When I put that statement in `tqdm`, **(this takes approximately 11 minutes to finish)** I see the speed as an iteration per second. Previously, I was trying to find sentiments of 10k tweets. **(that was taking very long time to compute)** Is there another endpoint which can return the sentiments in batches? (meaning multiple tweets at once?) Here is my code.
![image](https://user-images.githubusercontent.com/86305049/124282680-194bde80-db19-11eb-9a3f-de6b7f114234.png)

**Comment by avarone-github** [comment]
Hello, and sorry for the delay.
Natural Language API resources can be used in parallel, so one possibility is having more clients requesting them.
I'm closing the issue and reminding you that it is possible to write to api.support@expert.ai for support and special request.
