### ISSUE TITLE
binascii.Error: Incorrect padding 

### ISSUE THREAD

**Issue by Hilal-Urun** [therealexpertai/nlapi-python#16]
Hi when I try to analyse abstract text data which is from pubmed I get incorrect padding error. When I try to analyse smaller text it didn't give error, and the error comes from below line. Could you help me please? 
`output=output = client.full_analysis(body={"document": {"text": query_data[key]['abstract']}},
                                                       params={'language': language, 'resource': 'relevants'})`

**Comment by avarone-github** [comment]
Hi @Hilal-Urun, nice to meet you.
Which version of `expertai-nlapi` are you using? And which is the length of the text? Be aware that Natural Language API has an hard limit of 10KB per request.

**Comment by Hilal-Urun** [comment]
yes I also think that it is related to that. I am using expertai-nlapi 2.4.0 version

**Comment by avarone-github** [comment]
@Hilal-Urun, to analyze "big" texts you need to create smaller chunks (to have <10KB requests sent to the API), analyze each chunk and them "sum" the results.
Please let me know if this solves your problem. Also consider that v. 2.4.1 is available. It fixes an authorization issue when making consecutive calls, so maybe is not your case, but I'd would give it a try the same.

**Comment by Hilal-Urun** [comment]
Thanks a lot, first I’m going to try the new version if it won’t work I’m going to try first solution you suggest and I’m going to give feedback about that, thanks a lot again

**Comment by avarone-github** [comment]
@Hilal-Urun, you are welcome. Version 2.4.1 solves an issue that can happen with consecutive calls, but it doesn't change the hard limit of the underlying API, so for big texts you'll still need the split+join approach. See you.

**Comment by avarone-github** [comment]
Good to know @Hilal-Urun, thank you. I'm closing this issue.
