### ISSUE TITLE
No topics for one document

### ISSUE THREAD

**Issue by drfraser** [therealexpertai/nlapi-python#4]
Probably not a bug - out of 1600 documents, only this one (after a full analysis) returned a null set of topics. Other functions like mainSyncons and sentences had associated data. A note in the documentation that the output might contain 0 topics would be useful.

"I recently stayed at the Hard Rock Hotel in Chicago, Il. From the start, the experience was bad. The room was filthy, there were no towels, and the front desk did nothing to rectify the situation. I will never stay there again. I could not have been more dissatisfied."

I did a quick scan of the list of topics in the Developer website and it does look like none of them would have been triggered by this document. It is an interesting list and oddly specific for some categories. Are there any plans to expand it and do you know of Empath?   (https://github.com/Ejhfast/empath-client)

**Comment by swelcker** [comment]
I guess you talking about the media topics? If so, it is a categorization extension, they always can be empty (categories:[]) or have n entries. In your provided example Media Topis are empty, GeoTax provides 2 entries.

MediaTopics are a standardized taxonomy with regular updates (see https://iptc.org/standards/media-topics/). Very generic and used for media categorization, as the name implies. You can add or extend your own model with expert.ai studio

**Comment by drfraser** [comment]
No, I submitted this issue before the IPTC categorization functionality was added, so this was about the custom expert.ai topics functionality - https://docs.expert.ai/nlapi/latest/reference/topics/  

and https://docs.expert.ai/nlapi/latest/reference/output/keyphrase-extraction/   

That list of topics is KnowledgeGraph based so returning an empty list of topics ought to be expected. My comment was essentially about the documentation.
